# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$character$directory$git_branch$git_status'

# Inserts a blank line between shell prompts
add_newline = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[character]
format = ' 🚀 '
